spring:
  jpa:
    hibernate: # hibernate ?? ??
      ddl-auto: create
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true