spring:
  jpa:
    hibernate: # hibernate ?? ??
      ddl-auto: create
    properties: # property ?? ??
      hibernate: # hibernate property ??
        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    include: oauth

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true # 이거 설정 안해서 계속 한글이 ???로 떴음